import { useTranslations } from 'next-intl';

export default function KnowledgePage() {
  const t = useTranslations('Navigation');

  return (
    <div className="container mx-auto px-4 py-24 min-h-[80vh]">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-6xl font-bold mb-12 font-outfit uppercase tracking-tighter">Knowledge Base</h1>
        
        <div className="grid gap-6">
          {[
            { q: "What is a Deobank?", a: "A Deobank is a decentralized onchain bank that operates through smart contracts on the WeChain blockchain, ensuring transparency and user sovereignty." },
            { q: "How does MPC security work?", a: "Multi-Party Computation (MPC) splits your private key into fragments (User Share and Platform Share). Transactions require 2-of-2 signatures, preventing single points of failure." },
            { q: "What is the utility of $WFI?", a: "The $WFI token is the native asset of WeChain. It's used to pay network fees, participate in staking rewards, and govern the protocol's evolution." },
            { q: "How do I generate Energy?", a: "Energy is automatically generated by holding $WFI in your wallet. It can be used to offset transaction fees and purchase CBM units." }
          ].map((item, idx) => (
            <div key={idx} className="glass-panel p-8 hover:bg-white/5 transition-all group">
              <h3 className="text-xl font-bold mb-4 font-outfit tracking-tight group-hover:text-[#007AFF] transition-colors flex items-center gap-4">
                <span className="text-[#007AFF]">?</span> {item.q}
              </h3>
              <p className="text-white/50 leading-relaxed text-sm">{item.a}</p>
            </div>
          ))}
        </div>

        <div className="mt-16 p-8 glass-panel border-[#007AFF]/30 border-2 flex flex-col md:flex-row items-center justify-between gap-8">
          <div>
            <h4 className="text-xl font-bold mb-2 font-outfit uppercase tracking-tighter">GitBook Documentation</h4>
            <p className="text-white/40 text-sm">Deep dive into technical architecture and protocol specifications.</p>
          </div>
          <a href="https://gitbook.wefi.co/" target="_blank" rel="noopener noreferrer" className="px-8 py-3 rounded-full bg-[#007AFF] text-white text-sm font-bold uppercase tracking-widest transition-all shadow-blue-glow">Open GitBook</a>
        </div>
      </div>
    </div>
  );
}
